name: lff
version: '0.1.0'
summary: Simple and straightforward large files finder utility for *nix
description: |
  Simple and straightforward large files finder utility for *nix, optimize for human.

grade: stable
confinement: strict
base: core18

apps:
  lff:
    command: bin/lff

parts:
  lff:
    source: ./
    plugin: crystal