name: lff
type: app
version: '0.1.1'
summary: Simple and straightforward large files finder utility for *nix
description: |
  Simple and straightforward large files finder utility for *nix, optimize for human.

icon: snap/local/assets/find.png
license: MIT

base: core18
grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  lff:
    command: bin/lff

parts:
  lff:
    source: ./
    plugin: crystal
